'GitHub Workflow':
- changed-files:
  - any-glob-to-any-file:
    - '.github/**'

'Go':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.go'

'Dependencies':
- changed-files:
  - any-glob-to-any-file:
    - '**/go.mod'
    - '**/go.sum'

'Unit Test':
- changed-files:
  - any-glob-to-any-file:
    - '**/*_test.go'

'Documentation':
- changed-files:
  - any-glob-to-any-file:
    - '**/README.md'

'Docker':
- changed-files:
  - any-glob-to-any-file:
    - '**/Dockerfile*'