version: "2"
run:
  go: '1.24.2'
  modules-download-mode: readonly
  allow-parallel-runners: true
  timeout: 3m
linters:
  default: standard
  enable:
    - gosec
    - bodyclose
    - noctx
    - exhaustive
    - loggercheck
    - nilerr
    - paralleltest
    - sloglint
    - testifylint
    - thelper
    - tparallel
formatters:
  enable:
    - gofmt
    - goimports
issues:
  uniq-by-line: false
output:
  show-stats: true
