name: Go Test

on:
  workflow_call:

jobs:
  build-and-test:
    strategy:
        matrix:
          os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Github Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum
      - name: Run tests
        run: go test ./... -timeout 10s -race