name: Pull Request

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize

jobs:
  ci:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/ci.yaml